pipeline {
    agent {dockerfile true}
    stages {
        stage('DockerBuild') {
            steps ('Build file'){
                step(dir('/var/jenkins_home/workspace/demo123/DockerDemo/static-site') {
					[
                    $class: 'DockerBuilderPublisher',
                    cleanImages: false, 
                    cleanupWithJenkinsJobDelete: false,
                    dockerFileDirectory: 'DockerDemo/static-site/', 
                    pushOnSuccess: false,
                    tagsString: 'jenkinsdidit'
                    ]
				})

            }
        }
    }
}
