pipeline {
    agent {dockerfile true}
    stages {
        stage('DockerBuild') {
            steps ('Build file'){
                step(
                    [
                    $class: 'DockerBuilderPublisher',
                    cleanImages: false, 
                    cleanupWithJenkinsJobDelete: false,
                    dockerFileDirectory: 'DockerDemo/static-site/', 
                    pushOnSuccess: false,
                    tagsString: 'jenkinsdidit'
                    ]
                )
            }
        }
    }
}
